apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  namespace: repo-search
spec:
  strategy:
    type: Recreate
  template:
    spec:
      runtimeClassName: nvidia
      containers:
        - name: embedding-service
          env:
            - name: EMBEDDING_DEVICE
              value: cuda
            - name: GPU_REQUIRED
              value: "true"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          resources:
            limits:
              nvidia.com/gpu: "1"
