apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../k8s
  - runtimeclass-nvidia.yaml
  - dcgm-exporter.yaml
patches:
  - path: embedding-service-gpu-patch.yaml
  - path: prometheus-dcgm-patch.yaml
